kind: Namespace
apiVersion: v1 
metadata:
  name: erkan 
  labels:
    name: erkan

---
kind: RoleBinding  
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: erkan
  namespace: erkan
subjects:
- kind: User 
  name: erkan@linsenraum.de
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
